parameters:
  - name: variableRoot
    type: string
    default: "vars"
  - name: environments
    type: object
    default: []
  - name: variablesConfig
    type: object
    default: {}
  - name: pool
    type: object
    default: {}
  - name: dependsOnStages
    type: object
    default: []
  - name: additionalRepositories
    type: object
    default: []
  - name: useLockedSources
    type: boolean
    default: true

jobs:
  - job: validate_variable_includes
    displayName: Validate Variable Includes
    dependsOn: ${{ parameters.dependsOnStages }}
    steps:
      - checkout: PipelineCommon
        path: s/PipelineCommon
      - ${{ if eq(parameters.useLockedSources, true) }}:
          - template: ../../steps/download-artifact.yml@PipelineCommon
            parameters:
              displayName: Download source snapshot
              artifactName: source-snapshot
              downloadPath: $(Pipeline.Workspace)/s/self
      - ${{ if eq(parameters.useLockedSources, false) }}:
          - checkout: self
            path: s/self
      - ${{ if ne(coalesce(parameters.additionalRepositories, ''), '') }}:
          - ${{ each repo in parameters.additionalRepositories }}:
              - checkout: ${{ repo.alias }}
      - template: ../../steps/powershell.yml@PipelineCommon
        parameters:
          displayName: Preflight variable includes
          repoAlias: PipelineCommon
          script: validate_variable_includes.ps1
          arguments: >-
            -VariableRoot "${{ parameters.variableRoot }}"
            -EnvironmentsJson '${{ convertToJson(parameters.environments) }}'
            -VariablesConfigJson '${{ convertToJson(parameters.variablesConfig) }}'
