parameters:
  - name: variableRoot
    type: string
    default: 'vars'
  - name: environments
    type: object
    default: []
  - name: pool
    type: object
    default: {}
  - name: dependsOnStages
    type: object
    default: []
  - name: additionalRepositories
    type: object
    default: []

jobs:
  - job: validate_variable_includes
    displayName: Validate Variable Includes
    ${{ if gt(length(parameters.dependsOnStages), 0) }}:
      dependsOn: ${{ parameters.dependsOnStages }}
    pool:
      ${{ if ne(coalesce(parameters.pool.name, ''), '') }}:
        name: ${{ parameters.pool.name }}
      ${{ if and(eq(coalesce(parameters.pool.name, ''), ''), ne(coalesce(parameters.pool.vmImage, ''), '')) }}:
        vmImage: ${{ parameters.pool.vmImage }}

    steps:
      - checkout: none
      - checkout: PipelineCommon
      - ${{ if gt(length(parameters.additionalRepositories), 0) }}:
        - ${{ each repo in parameters.additionalRepositories }}:
          - checkout: ${{ repo.alias }}
      - template: ../../steps/powershell.yml@PipelineCommon
        parameters:
          displayName: Preflight variable includes
          repoAlias: PipelineCommon
          script: validate_variable_includes.ps1
          arguments: >-
            -VariableRoot "${{ parameters.variableRoot }}"
            -Environments ${{ each env in parameters.environments }}:@{ name='${{ env.name }}' }
