parameters:
  - name: actionGroups
    type: object
    default: []
  - name: pool
    type: object
    default: {}
  - name: dependsOnStages
    type: object
    default: []
  - name: additionalRepositories
    type: object
    default: []
  - name: keyVault
    type: object
    default: {}
  - name: serviceConnection
    type: string
    default: ''

jobs:
  - job: validate_bicep
    displayName: Validate BICEP
    ${{ if gt(length(parameters.dependsOnStages), 0) }}:
      dependsOn: ${{ parameters.dependsOnStages }}
    pool:
      ${{ if ne(coalesce(parameters.pool.name, ''), '') }}:
        name: ${{ parameters.pool.name }}
      ${{ if and(eq(coalesce(parameters.pool.name, ''), ''), ne(coalesce(parameters.pool.vmImage, ''), '')) }}:
        vmImage: ${{ parameters.pool.vmImage }}

    steps:
      - checkout: none
      - checkout: PipelineCommon
      - ${{ if gt(length(parameters.additionalRepositories), 0) }}:
        - ${{ each repo in parameters.additionalRepositories }}:
          - checkout: ${{ repo.alias }}
      - ${{ if ne(coalesce(parameters.keyVault.name, ''), '') }}:
        - template: ../../steps/import-keyvault-secrets.yml@PipelineCommon
          parameters:
            displayName: Import Key Vault Secrets
            azureSubscription: ${{ parameters.serviceConnection }}
            keyVaultName: ${{ parameters.keyVault.name }}
            secretsFilter: ${{ coalesce(parameters.keyVault.secretsFilter, '*') }}
      - template: ../../steps/download-artifact.yml@PipelineCommon
        parameters:
          displayName: Download source snapshot
          artifactName: source-snapshot
          downloadPath: $(Pipeline.Workspace)/locked-sources
      - ${{ each actionGroup in parameters.actionGroups }}:
        - ${{ if gt(length(actionGroup.actions), 0) }}:
          - ${{ each action in actionGroup.actions }}:
            - ${{ if eq(action.type, 'bicep') }}:
              - template: ../../steps/azurecli.yml@PipelineCommon
                parameters:
                  displayName: Bicep Lint (${{ coalesce(action.displayName, upper(replace(coalesce(action.name, 'BICEP'), '_', ' '))) }})
                  repoAlias: PipelineCommon
                  script: bicep_lint.ps1
                  arguments: -SearchPath "$(Pipeline.Workspace)/locked-sources"
