parameters:
  - name: environments
    type: object
    default: []
  - name: pool
    type: object
    default: {}
  - name: dependsOnStages
    type: object
    default: []
  - name: additionalRepositories
    type: object
    default: []
  - name: enableProduction
    type: boolean
    default: false

jobs:
  - job: validate_branch_allowlist
    displayName: Validate Branch Allow-List
    dependsOn: ${{ parameters.dependsOnStages }}
    steps:
      - checkout: PipelineCommon
      - ${{ if gt(length(parameters.additionalRepositories), 0) }}:
          - ${{ each r in parameters.additionalRepositories }}:
              - checkout: ${{ r.alias }}
      - ${{ each env in parameters.environments }}:
          - ${{ if ne(env.skipEnvironment, true) }}:
              - ${{ if or(ne(env.class, 'production'), eq(coalesce(parameters.configuration.enableProduction, false), true)) }}:
                  - template: ../../steps/powershell.yml@PipelineCommon
                    parameters:
                      displayName: Check allowed branches (${{ env.name }})
                      repoAlias: PipelineCommon
                      script: branch_check.ps1
                      arguments: >-
                        -AllowedBranchesJson '${{ convertToJson(env.allowedBranches) }}'
