# Run Conditions
trigger:
  branches:
    include:
      - main
pr: none

parameters:
  # Global flags
  - name: drInvocation
    displayName: "Invoke Pipeline DR Operation"
    type: boolean
    default: false

extends:
  template: pipeline-common.settings.yml
  parameters:
    drInvocation: ${{ parameters.drInvocation }}
    actionGroups:
      - name: github_release
        type: powershell
        kind: release
        environments:
          - dev
        useLockedSources: false
        actions:
          - name: create_tag
            scriptPath: scripts/release_semver.ps1
            arguments: "-ReleaseNotesFile $(Build.SourcesDirectory)/release/release-notes.md"
          - name: update_dispatcher
            condition: eq(variables['ReleaseSkip'], 'false')
            scriptPath: scripts/update_dispatcher_ref.ps1
            arguments: "-PipelineCommonTag $(ReleaseTag) -GitHubRepository wesley-trust/pipeline-dispatcher"
