# Settings for Bicep + post-deploy Pester example

parameters:
  - name: actionGroups
    type: object
    default: []
  - name: enableProduction
    type: boolean
    default: false
  - name: runReviewStage
    type: boolean
    default: true
  - name: drInvocation
    type: boolean
    default: false
  - name: skip_dev
    type: boolean
    default: false
  - name: skip_qa
    type: boolean
    default: false
  - name: skip_preprod
    type: boolean
    default: false
  - name: skip_prod
    type: boolean
    default: false

extends:
  template: ../dispatcher/dispatcher.yml
  parameters:
    configuration:
      environments:
        - name: dev
          class: development
          primaryRegion: weu
          secondaryRegions: [ neu ]
          drRegion: neu
          allowedBranches: [ '*' ]
          pool: { vmImage: 'ubuntu-latest' }
          skipEnvironment: ${{ parameters.skip_dev }}
          poolRegionDemand: false
        - name: qa
          class: test
          dependsOn: dev
          dependsOnPrimaryRegion: weu
          dependsOnDRRegion: neu
          primaryRegion: weu
          allowedBranches: [ 'main', 'release/*' ]
          pool: { vmImage: 'ubuntu-latest' }
          skipEnvironment: ${{ parameters.skip_qa }}
          poolRegionDemand: false
        - name: preprod
          class: acceptance
          dependsOn: test
          dependsOnPrimaryRegion: weu
          dependsOnDRRegion: neu
          primaryRegion: weu
          allowedBranches: [ 'main', 'release/*' ]
          pool: { vmImage: 'ubuntu-latest' }
          skipEnvironment: ${{ parameters.skip_preprod }}
          poolRegionDemand: false
        - name: prod
          class: production
          dependsOn: preprod
          dependsOnPrimaryRegion: weu
          dependsOnDRRegion: neu
          primaryRegion: weu
          secondaryRegions: [ neu ]
          drRegion: neu
          allowedBranches: [ 'main', 'release/*' ]
          pool: { name: 'Prod-SelfHosted' }
          skipEnvironment: ${{ parameters.skip_prod }}
          poolRegionDemand: true
      actionGroups: ${{ parameters.actionGroups }}
      enableProduction: ${{ parameters.enableProduction }}
      runReviewStage: ${{ parameters.runReviewStage }}
      drInvocation: ${{ parameters.drInvocation }}
      variableRoot: examples/consumer/vars
      variables:
        includeCommon: true
        includeEnv: true
        includeEnvRegion: true
        includeRegionOnly: true
      defaultPool: { vmImage: 'ubuntu-latest' }
      variableGroups: [ 'Common-Variables' ]
      validation:
        enableVariableIncludes: false
      additionalRepositories:
        - alias: Modules
          name: org/project.modules
          ref: refs/heads/main
      keyVault:
        name: kv-example
        secretsFilter: 'app-*'
