# Setup: common preparation
# - Publishes a snapshot of the self repository as a pipeline artifact for
#   route-to-live integrity. All later jobs download this snapshot instead of
#   re-checking out fresh sources.

parameters:
  - name: name
    type: string
    default: setup_common
  - name: displayName
    type: string
    default: "Setup: Common"
  - name: artifactName
    type: string
    default: source-snapshot
  - name: pool
    type: object
    default: {}

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    steps:
      - checkout: self
      - checkout: PipelineCommon

      - template: ../../steps/publish-artifact.yml@PipelineCommon
        parameters:
          displayName: Publish Source Snapshot
          artifactName: ${{ parameters.artifactName }}
          targetPath: $(Build.SourcesDirectory)
