# Initialise stage: prepares shared tooling and source snapshot for RTL integrity.
# Jobs:
# - initialise_common: always publishes the self repo snapshot
# - initialise_terraform: installs Terraform (when version specified)
# - initialise_bicep: ensures Bicep CLI is available (only if Bicep task is used)

parameters:
  - name: environmentName
    type: string
  - name: serviceConnection
    type: string
    default: ""
  - name: pool
    type: object
    default: {}
  - name: terraformVersion
    type: string
    default: ""
  - name: dependsOnStages
    type: object
    default: []

stages:
  - stage: initialise_${{ parameters.environmentName }}
    ${{ if ne(parameters.environmentName, 'global') }}:
      displayName: "Initialise: ${{ upper(parameters.environmentName) }}"
    ${{ else }}:
      displayName: "Initialise"
    # ${{ if gt(length(coalesce(parameters.dependsOnStages, '')), 0) }}:
    #   dependsOn: ${{ parameters.dependsOnStages }}
    ${{ if ne(coalesce(parameters.pool.name, ''), '') }}:
      pool:
        name: ${{ parameters.pool.name }}
    ${{ elseif ne(coalesce(parameters.pool.vmImage, ''), '') }}:
      pool:
        vmImage: ${{ parameters.pool.vmImage }}
    jobs:
      - template: ../jobs/initialise/initialise-common.yml@PipelineCommon

      # Optional tooling setup jobs
      - template: ../jobs/initialise/initialise-bicep.yml@PipelineCommon
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}

      # - template: ../jobs/initialise/initialise-terraform.yml@PipelineCommon
      #   parameters:
      #     terraformVersion: ${{ parameters.terraformVersion }}
