# Setup: Terraform installation

parameters:
  - name: name
    type: string
    default: setup_terraform
  - name: displayName
    type: string
    default: "Setup: Terraform"
  - name: terraformVersion
    type: string
    default: ""
  - name: pool
    type: object
    default: {}

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    condition: and(succeeded(), ne('${{ parameters.terraformVersion }}',''))
    steps:
      - checkout: PipelineCommon

      - template: ../steps/azurecli.yml@PipelineCommon
        parameters:
          displayName: Install Terraform ${{ parameters.terraformVersion }}
          repoAlias: PipelineCommon
          script: setup_terraform.ps1
          arguments: -Version ${{ parameters.terraformVersion }}
