parameters:
  - name: name
    type: string
    default: initialise_common
  - name: displayName
    type: string
    default: "Initialise Common"
  - name: artifactName
    type: string
    default: source-snapshot
  - name: pool
    type: object
    default: {}

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    steps:
      - checkout: self
        path: s/self
      - checkout: PipelineCommon
        path: s/PipelineCommon

      - template: ../../steps/publish-artifact.yml@PipelineCommon
        parameters:
          displayName: Publish Source Snapshot
          artifactName: ${{ parameters.artifactName }}
          targetPath: $(Pipeline.Workspace)/s/self
